### ISSUE TITLE
Show action config on job detail page

### ISSUE THREAD

**Issue by evansd** [opensafely-core/job-server#427]
This is very much a nice-to-have convenience feature, but it struck me that it's probably possible (given that we pull in and parse `project.yaml` anyway) to display the configuration for the corresponding action.

So, for example, somewhere on this page here:

![Screenshot from 2021-03-19 18-30-58](https://user-images.githubusercontent.com/19630/111827068-5d580200-88e1-11eb-9e49-1ebb516524d2.png)

This config would be embedded
```
  anODDS_MOD:
    run: stata-mp:latest analysis/an_logit_models.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_logit_models.log
        table1text: output/table3_abs_risk.txt
        table1xlsx: output/table3_abs_risk.xlsx
```

**Super bonus feature**: parse the `run` line for anything that looks like a script name and make it a link to the corresponding file on github (as of the relevant commit).

This would make it really easy to get to the code which was run for a given action in a project you know nothing about.
